version: '3.8'
services:
  postgres:
    image: pgvector/pgvector:pg15
    container_name: expense_tracker
    environment:
      POSTGRES_USER: orionita230
      POSTGRES_PASSWORD: dreinjua&/3&kertuyaqUhasg!!m3tr59
      POSTGRES_DB: expense_tracker
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: